//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the lidar_team_morai package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __lidar_team_morai__ST_HYPER_PARAMETER_MORAICONFIG_H__
#define __lidar_team_morai__ST_HYPER_PARAMETER_MORAICONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace lidar_team_morai
{
  class st_hyper_parameter_moraiConfigStatics;

  class st_hyper_parameter_moraiConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(st_hyper_parameter_moraiConfig &config, const st_hyper_parameter_moraiConfig &max, const st_hyper_parameter_moraiConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const st_hyper_parameter_moraiConfig &config1, const st_hyper_parameter_moraiConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, st_hyper_parameter_moraiConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const st_hyper_parameter_moraiConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, st_hyper_parameter_moraiConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const st_hyper_parameter_moraiConfig &config) const = 0;
      virtual void getValue(const st_hyper_parameter_moraiConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T st_hyper_parameter_moraiConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T st_hyper_parameter_moraiConfig::* field;

      virtual void clamp(st_hyper_parameter_moraiConfig &config, const st_hyper_parameter_moraiConfig &max, const st_hyper_parameter_moraiConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const st_hyper_parameter_moraiConfig &config1, const st_hyper_parameter_moraiConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, st_hyper_parameter_moraiConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const st_hyper_parameter_moraiConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, st_hyper_parameter_moraiConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const st_hyper_parameter_moraiConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const st_hyper_parameter_moraiConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, st_hyper_parameter_moraiConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, st_hyper_parameter_moraiConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<st_hyper_parameter_moraiConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(st_hyper_parameter_moraiConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("st_minPoints"==(*_i)->name){st_minPoints = boost::any_cast<int>(val);}
        if("st_epsilon"==(*_i)->name){st_epsilon = boost::any_cast<double>(val);}
        if("st_minClusterSize"==(*_i)->name){st_minClusterSize = boost::any_cast<int>(val);}
        if("st_maxClusterSize"==(*_i)->name){st_maxClusterSize = boost::any_cast<double>(val);}
        if("st_xMinROI"==(*_i)->name){st_xMinROI = boost::any_cast<double>(val);}
        if("st_xMaxROI"==(*_i)->name){st_xMaxROI = boost::any_cast<double>(val);}
        if("st_yMinROI"==(*_i)->name){st_yMinROI = boost::any_cast<double>(val);}
        if("st_yMaxROI"==(*_i)->name){st_yMaxROI = boost::any_cast<double>(val);}
        if("st_zMinROI"==(*_i)->name){st_zMinROI = boost::any_cast<double>(val);}
        if("st_zMaxROI"==(*_i)->name){st_zMaxROI = boost::any_cast<double>(val);}
        if("st_xMinBoundingBox"==(*_i)->name){st_xMinBoundingBox = boost::any_cast<double>(val);}
        if("st_xMaxBoundingBox"==(*_i)->name){st_xMaxBoundingBox = boost::any_cast<double>(val);}
        if("st_yMinBoundingBox"==(*_i)->name){st_yMinBoundingBox = boost::any_cast<double>(val);}
        if("st_yMaxBoundingBox"==(*_i)->name){st_yMaxBoundingBox = boost::any_cast<double>(val);}
        if("st_zMinBoundingBox"==(*_i)->name){st_zMinBoundingBox = boost::any_cast<double>(val);}
        if("st_zMaxBoundingBox"==(*_i)->name){st_zMaxBoundingBox = boost::any_cast<double>(val);}
      }
    }

    int st_minPoints;
double st_epsilon;
int st_minClusterSize;
double st_maxClusterSize;
double st_xMinROI;
double st_xMaxROI;
double st_yMinROI;
double st_yMaxROI;
double st_zMinROI;
double st_zMaxROI;
double st_xMinBoundingBox;
double st_xMaxBoundingBox;
double st_yMinBoundingBox;
double st_yMaxBoundingBox;
double st_zMinBoundingBox;
double st_zMaxBoundingBox;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int st_minPoints;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_epsilon;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int st_minClusterSize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_maxClusterSize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_xMinROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_xMaxROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_yMinROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_yMaxROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_zMinROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_zMaxROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_xMinBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_xMaxBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_yMinBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_yMaxBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_zMinBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double st_zMaxBoundingBox;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("st_hyper_parameter_moraiConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const st_hyper_parameter_moraiConfig &__max__ = __getMax__();
      const st_hyper_parameter_moraiConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const st_hyper_parameter_moraiConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const st_hyper_parameter_moraiConfig &__getDefault__();
    static const st_hyper_parameter_moraiConfig &__getMax__();
    static const st_hyper_parameter_moraiConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const st_hyper_parameter_moraiConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void st_hyper_parameter_moraiConfig::ParamDescription<std::string>::clamp(st_hyper_parameter_moraiConfig &config, const st_hyper_parameter_moraiConfig &max, const st_hyper_parameter_moraiConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class st_hyper_parameter_moraiConfigStatics
  {
    friend class st_hyper_parameter_moraiConfig;

    st_hyper_parameter_moraiConfigStatics()
    {
st_hyper_parameter_moraiConfig::GroupDescription<st_hyper_parameter_moraiConfig::DEFAULT, st_hyper_parameter_moraiConfig> Default("Default", "", 0, 0, true, &st_hyper_parameter_moraiConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_minPoints = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_minPoints = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_minPoints = 30;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<int>("st_minPoints", "int", 0, "st_minPoints", "", &st_hyper_parameter_moraiConfig::st_minPoints)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<int>("st_minPoints", "int", 0, "st_minPoints", "", &st_hyper_parameter_moraiConfig::st_minPoints)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_epsilon = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_epsilon = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_epsilon = 0.4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_epsilon", "double", 0, "st_epsilon", "", &st_hyper_parameter_moraiConfig::st_epsilon)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_epsilon", "double", 0, "st_epsilon", "", &st_hyper_parameter_moraiConfig::st_epsilon)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_minClusterSize = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_minClusterSize = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_minClusterSize = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<int>("st_minClusterSize", "int", 0, "st_minClusterSize", "", &st_hyper_parameter_moraiConfig::st_minClusterSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<int>("st_minClusterSize", "int", 0, "st_minClusterSize", "", &st_hyper_parameter_moraiConfig::st_minClusterSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_maxClusterSize = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_maxClusterSize = 100000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_maxClusterSize = 10000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_maxClusterSize", "double", 0, "st_maxClusterSize", "", &st_hyper_parameter_moraiConfig::st_maxClusterSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_maxClusterSize", "double", 0, "st_maxClusterSize", "", &st_hyper_parameter_moraiConfig::st_maxClusterSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_xMinROI = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_xMinROI = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_xMinROI = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_xMinROI", "double", 0, "st_xMinROI", "", &st_hyper_parameter_moraiConfig::st_xMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_xMinROI", "double", 0, "st_xMinROI", "", &st_hyper_parameter_moraiConfig::st_xMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_xMaxROI = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_xMaxROI = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_xMaxROI = 15.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_xMaxROI", "double", 0, "st_xMaxROI", "", &st_hyper_parameter_moraiConfig::st_xMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_xMaxROI", "double", 0, "st_xMaxROI", "", &st_hyper_parameter_moraiConfig::st_xMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_yMinROI = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_yMinROI = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_yMinROI = -1.3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_yMinROI", "double", 0, "st_yMinROI", "", &st_hyper_parameter_moraiConfig::st_yMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_yMinROI", "double", 0, "st_yMinROI", "", &st_hyper_parameter_moraiConfig::st_yMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_yMaxROI = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_yMaxROI = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_yMaxROI = 1.3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_yMaxROI", "double", 0, "st_yMaxROI", "", &st_hyper_parameter_moraiConfig::st_yMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_yMaxROI", "double", 0, "st_yMaxROI", "", &st_hyper_parameter_moraiConfig::st_yMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_zMinROI = -2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_zMinROI = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_zMinROI = -0.44;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_zMinROI", "double", 0, "st_zMinROI", "", &st_hyper_parameter_moraiConfig::st_zMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_zMinROI", "double", 0, "st_zMinROI", "", &st_hyper_parameter_moraiConfig::st_zMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_zMaxROI = -2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_zMaxROI = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_zMaxROI = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_zMaxROI", "double", 0, "st_zMaxROI", "", &st_hyper_parameter_moraiConfig::st_zMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_zMaxROI", "double", 0, "st_zMaxROI", "", &st_hyper_parameter_moraiConfig::st_zMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_xMinBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_xMinBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_xMinBoundingBox = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_xMinBoundingBox", "double", 0, "st_xMinBoundingBox", "", &st_hyper_parameter_moraiConfig::st_xMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_xMinBoundingBox", "double", 0, "st_xMinBoundingBox", "", &st_hyper_parameter_moraiConfig::st_xMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_xMaxBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_xMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_xMaxBoundingBox = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_xMaxBoundingBox", "double", 0, "st_xMaxBoundingBox", "", &st_hyper_parameter_moraiConfig::st_xMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_xMaxBoundingBox", "double", 0, "st_xMaxBoundingBox", "", &st_hyper_parameter_moraiConfig::st_xMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_yMinBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_yMinBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_yMinBoundingBox = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_yMinBoundingBox", "double", 0, "st_yMinBoundingBox", "", &st_hyper_parameter_moraiConfig::st_yMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_yMinBoundingBox", "double", 0, "st_yMinBoundingBox", "", &st_hyper_parameter_moraiConfig::st_yMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_yMaxBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_yMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_yMaxBoundingBox = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_yMaxBoundingBox", "double", 0, "st_yMaxBoundingBox", "", &st_hyper_parameter_moraiConfig::st_yMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_yMaxBoundingBox", "double", 0, "st_yMaxBoundingBox", "", &st_hyper_parameter_moraiConfig::st_yMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_zMinBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_zMinBoundingBox = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_zMinBoundingBox = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_zMinBoundingBox", "double", 0, "st_zMinBoundingBox", "", &st_hyper_parameter_moraiConfig::st_zMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_zMinBoundingBox", "double", 0, "st_zMinBoundingBox", "", &st_hyper_parameter_moraiConfig::st_zMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.st_zMaxBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.st_zMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.st_zMaxBoundingBox = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_zMaxBoundingBox", "double", 0, "st_zMaxBoundingBox", "", &st_hyper_parameter_moraiConfig::st_zMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr(new st_hyper_parameter_moraiConfig::ParamDescription<double>("st_zMaxBoundingBox", "double", 0, "st_zMaxBoundingBox", "", &st_hyper_parameter_moraiConfig::st_zMaxBoundingBox)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(st_hyper_parameter_moraiConfig::AbstractGroupDescriptionConstPtr(new st_hyper_parameter_moraiConfig::GroupDescription<st_hyper_parameter_moraiConfig::DEFAULT, st_hyper_parameter_moraiConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<st_hyper_parameter_moraiConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<st_hyper_parameter_moraiConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    st_hyper_parameter_moraiConfig __max__;
    st_hyper_parameter_moraiConfig __min__;
    st_hyper_parameter_moraiConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const st_hyper_parameter_moraiConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static st_hyper_parameter_moraiConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &st_hyper_parameter_moraiConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const st_hyper_parameter_moraiConfig &st_hyper_parameter_moraiConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const st_hyper_parameter_moraiConfig &st_hyper_parameter_moraiConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const st_hyper_parameter_moraiConfig &st_hyper_parameter_moraiConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<st_hyper_parameter_moraiConfig::AbstractParamDescriptionConstPtr> &st_hyper_parameter_moraiConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<st_hyper_parameter_moraiConfig::AbstractGroupDescriptionConstPtr> &st_hyper_parameter_moraiConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const st_hyper_parameter_moraiConfigStatics *st_hyper_parameter_moraiConfig::__get_statics__()
  {
    const static st_hyper_parameter_moraiConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = st_hyper_parameter_moraiConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ST_HYPER_PARAMETER_MORAIRECONFIGURATOR_H__
