// Generated by gencpp from file obstacles_detector/WaypointList.msg
// DO NOT EDIT!


#ifndef OBSTACLES_DETECTOR_MESSAGE_WAYPOINTLIST_H
#define OBSTACLES_DETECTOR_MESSAGE_WAYPOINTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <obstacles_detector/Waypoint.h>

namespace obstacles_detector
{
template <class ContainerAllocator>
struct WaypointList_
{
  typedef WaypointList_<ContainerAllocator> Type;

  WaypointList_()
    : header()
    , list()  {
    }
  WaypointList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::obstacles_detector::Waypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::obstacles_detector::Waypoint_<ContainerAllocator> >::other >  _list_type;
  _list_type list;





  typedef boost::shared_ptr< ::obstacles_detector::WaypointList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacles_detector::WaypointList_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointList_

typedef ::obstacles_detector::WaypointList_<std::allocator<void> > WaypointList;

typedef boost::shared_ptr< ::obstacles_detector::WaypointList > WaypointListPtr;
typedef boost::shared_ptr< ::obstacles_detector::WaypointList const> WaypointListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacles_detector::WaypointList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacles_detector::WaypointList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::obstacles_detector::WaypointList_<ContainerAllocator1> & lhs, const ::obstacles_detector::WaypointList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.list == rhs.list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::obstacles_detector::WaypointList_<ContainerAllocator1> & lhs, const ::obstacles_detector::WaypointList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace obstacles_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::obstacles_detector::WaypointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacles_detector::WaypointList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacles_detector::WaypointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacles_detector::WaypointList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacles_detector::WaypointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacles_detector::WaypointList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacles_detector::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4ae0fee55df3baa0344e6959a295b8c";
  }

  static const char* value(const ::obstacles_detector::WaypointList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4ae0fee55df3baaULL;
  static const uint64_t static_value2 = 0x0344e6959a295b8cULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacles_detector::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacles_detector/WaypointList";
  }

  static const char* value(const ::obstacles_detector::WaypointList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacles_detector::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"Waypoint[] list \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: obstacles_detector/Waypoint\n"
"Header header\n"
"\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::obstacles_detector::WaypointList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacles_detector::WaypointList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacles_detector::WaypointList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacles_detector::WaypointList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "list[]" << std::endl;
    for (size_t i = 0; i < v.list.size(); ++i)
    {
      s << indent << "  list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::obstacles_detector::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLES_DETECTOR_MESSAGE_WAYPOINTLIST_H
