// Generated by gencpp from file avoid_obstacle/TrueObstacles.msg
// DO NOT EDIT!


#ifndef AVOID_OBSTACLE_MESSAGE_TRUEOBSTACLES_H
#define AVOID_OBSTACLE_MESSAGE_TRUEOBSTACLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avoid_obstacle
{
template <class ContainerAllocator>
struct TrueObstacles_
{
  typedef TrueObstacles_<ContainerAllocator> Type;

  TrueObstacles_()
    : detected(0)  {
    }
  TrueObstacles_(const ContainerAllocator& _alloc)
    : detected(0)  {
  (void)_alloc;
    }



   typedef int32_t _detected_type;
  _detected_type detected;





  typedef boost::shared_ptr< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> const> ConstPtr;

}; // struct TrueObstacles_

typedef ::avoid_obstacle::TrueObstacles_<std::allocator<void> > TrueObstacles;

typedef boost::shared_ptr< ::avoid_obstacle::TrueObstacles > TrueObstaclesPtr;
typedef boost::shared_ptr< ::avoid_obstacle::TrueObstacles const> TrueObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avoid_obstacle::TrueObstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avoid_obstacle::TrueObstacles_<ContainerAllocator1> & lhs, const ::avoid_obstacle::TrueObstacles_<ContainerAllocator2> & rhs)
{
  return lhs.detected == rhs.detected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avoid_obstacle::TrueObstacles_<ContainerAllocator1> & lhs, const ::avoid_obstacle::TrueObstacles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avoid_obstacle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b915f91311c8f5d6b235ceb818d53f80";
  }

  static const char* value(const ::avoid_obstacle::TrueObstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb915f91311c8f5d6ULL;
  static const uint64_t static_value2 = 0xb235ceb818d53f80ULL;
};

template<class ContainerAllocator>
struct DataType< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avoid_obstacle/TrueObstacles";
  }

  static const char* value(const ::avoid_obstacle::TrueObstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 detected\n"
;
  }

  static const char* value(const ::avoid_obstacle::TrueObstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrueObstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avoid_obstacle::TrueObstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avoid_obstacle::TrueObstacles_<ContainerAllocator>& v)
  {
    s << indent << "detected: ";
    Printer<int32_t>::stream(s, indent + "  ", v.detected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVOID_OBSTACLE_MESSAGE_TRUEOBSTACLES_H
