// Generated by gencpp from file lidar_team_beta/ObjectInfo.msg
// DO NOT EDIT!


#ifndef LIDAR_TEAM_BETA_MESSAGE_OBJECTINFO_H
#define LIDAR_TEAM_BETA_MESSAGE_OBJECTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_team_beta
{
template <class ContainerAllocator>
struct ObjectInfo_
{
  typedef ObjectInfo_<ContainerAllocator> Type;

  ObjectInfo_()
    : total(0)
    , x()
    , y()
    , r()  {
      x.assign(0.0);

      y.assign(0.0);

      r.assign(0.0);
  }
  ObjectInfo_(const ContainerAllocator& _alloc)
    : total(0)
    , x()
    , y()
    , r()  {
  (void)_alloc;
      x.assign(0.0);

      y.assign(0.0);

      r.assign(0.0);
  }



   typedef uint16_t _total_type;
  _total_type total;

   typedef boost::array<double, 30>  _x_type;
  _x_type x;

   typedef boost::array<double, 30>  _y_type;
  _y_type y;

   typedef boost::array<double, 30>  _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInfo_

typedef ::lidar_team_beta::ObjectInfo_<std::allocator<void> > ObjectInfo;

typedef boost::shared_ptr< ::lidar_team_beta::ObjectInfo > ObjectInfoPtr;
typedef boost::shared_ptr< ::lidar_team_beta::ObjectInfo const> ObjectInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_team_beta::ObjectInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_team_beta::ObjectInfo_<ContainerAllocator1> & lhs, const ::lidar_team_beta::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return lhs.total == rhs.total &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.r == rhs.r;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_team_beta::ObjectInfo_<ContainerAllocator1> & lhs, const ::lidar_team_beta::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_team_beta

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93078c6225133f2d27cf0a8b110ab31c";
  }

  static const char* value(const ::lidar_team_beta::ObjectInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93078c6225133f2dULL;
  static const uint64_t static_value2 = 0x27cf0a8b110ab31cULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_team_beta/ObjectInfo";
  }

  static const char* value(const ::lidar_team_beta::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 total\n"
"float64[30] x\n"
"float64[30] y\n"
"float64[30] r\n"
;
  }

  static const char* value(const ::lidar_team_beta::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_team_beta::ObjectInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_team_beta::ObjectInfo_<ContainerAllocator>& v)
  {
    s << indent << "total: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.total);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "r[]" << std::endl;
    for (size_t i = 0; i < v.r.size(); ++i)
    {
      s << indent << "  r[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.r[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_TEAM_BETA_MESSAGE_OBJECTINFO_H
