// Generated by gencpp from file race/drive_values.msg
// DO NOT EDIT!


#ifndef RACE_MESSAGE_DRIVE_VALUES_H
#define RACE_MESSAGE_DRIVE_VALUES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace race
{
template <class ContainerAllocator>
struct drive_values_
{
  typedef drive_values_<ContainerAllocator> Type;

  drive_values_()
    : throttle(0)
    , steering(0.0)
    , brake(0.0)  {
    }
  drive_values_(const ContainerAllocator& _alloc)
    : throttle(0)
    , steering(0.0)
    , brake(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _throttle_type;
  _throttle_type throttle;

   typedef double _steering_type;
  _steering_type steering;

   typedef double _brake_type;
  _brake_type brake;





  typedef boost::shared_ptr< ::race::drive_values_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::race::drive_values_<ContainerAllocator> const> ConstPtr;

}; // struct drive_values_

typedef ::race::drive_values_<std::allocator<void> > drive_values;

typedef boost::shared_ptr< ::race::drive_values > drive_valuesPtr;
typedef boost::shared_ptr< ::race::drive_values const> drive_valuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::race::drive_values_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::race::drive_values_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::race::drive_values_<ContainerAllocator1> & lhs, const ::race::drive_values_<ContainerAllocator2> & rhs)
{
  return lhs.throttle == rhs.throttle &&
    lhs.steering == rhs.steering &&
    lhs.brake == rhs.brake;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::race::drive_values_<ContainerAllocator1> & lhs, const ::race::drive_values_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace race

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::race::drive_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::race::drive_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::race::drive_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::race::drive_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::race::drive_values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::race::drive_values_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::race::drive_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1426dadf0c13360c5b48826f6ea8e4b3";
  }

  static const char* value(const ::race::drive_values_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1426dadf0c13360cULL;
  static const uint64_t static_value2 = 0x5b48826f6ea8e4b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::race::drive_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "race/drive_values";
  }

  static const char* value(const ::race::drive_values_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::race::drive_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 throttle\n"
"float64 steering\n"
"float64 brake\n"
;
  }

  static const char* value(const ::race::drive_values_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::race::drive_values_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.steering);
      stream.next(m.brake);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drive_values_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::race::drive_values_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::race::drive_values_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
    s << indent << "brake: ";
    Printer<double>::stream(s, indent + "  ", v.brake);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACE_MESSAGE_DRIVE_VALUES_H
