yolo_model:

  config_file:
    name: yolov3_final.cfg
  weight_file:
    name: yolov3_final_best1.weights #yolov3_final.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - _
      - _
      - _
      - _
      - _
      - _
      - _
      - _
      - _
      - _
      - B1
      - B2
      - B3
      - A1
      - A2
      - A3
