yolo_model:

  config_file:
    name: yolov2_final.cfg
  weight_file:
    name: yolov2_final1.weights #yolov3_final.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - 3 red
      - 3 yellow
      - 3 green
      - 3 left
      - 4 red
      - 4 green
      - 4 yellow
      - 4 redleft
      - 4 greenleft
      - 4 redyellow
      - B1
      - B2
      - B3
      - A1
      - A2
      - A3
