//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the lidar_team_erp42 package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __lidar_team_erp42__SMALL_ST_HYPER_PARAMETERCONFIG_H__
#define __lidar_team_erp42__SMALL_ST_HYPER_PARAMETERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace lidar_team_erp42
{
  class small_st_hyper_parameterConfigStatics;

  class small_st_hyper_parameterConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(small_st_hyper_parameterConfig &config, const small_st_hyper_parameterConfig &max, const small_st_hyper_parameterConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const small_st_hyper_parameterConfig &config1, const small_st_hyper_parameterConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, small_st_hyper_parameterConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const small_st_hyper_parameterConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, small_st_hyper_parameterConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const small_st_hyper_parameterConfig &config) const = 0;
      virtual void getValue(const small_st_hyper_parameterConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T small_st_hyper_parameterConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T small_st_hyper_parameterConfig::* field;

      virtual void clamp(small_st_hyper_parameterConfig &config, const small_st_hyper_parameterConfig &max, const small_st_hyper_parameterConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const small_st_hyper_parameterConfig &config1, const small_st_hyper_parameterConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, small_st_hyper_parameterConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const small_st_hyper_parameterConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, small_st_hyper_parameterConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const small_st_hyper_parameterConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const small_st_hyper_parameterConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, small_st_hyper_parameterConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, small_st_hyper_parameterConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<small_st_hyper_parameterConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(small_st_hyper_parameterConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("small_st_minPoints"==(*_i)->name){small_st_minPoints = boost::any_cast<int>(val);}
        if("small_st_epsilon"==(*_i)->name){small_st_epsilon = boost::any_cast<double>(val);}
        if("small_st_minClusterSize"==(*_i)->name){small_st_minClusterSize = boost::any_cast<int>(val);}
        if("small_st_maxClusterSize"==(*_i)->name){small_st_maxClusterSize = boost::any_cast<double>(val);}
        if("small_st_xMinROI"==(*_i)->name){small_st_xMinROI = boost::any_cast<double>(val);}
        if("small_st_xMaxROI"==(*_i)->name){small_st_xMaxROI = boost::any_cast<double>(val);}
        if("small_st_yMinROI"==(*_i)->name){small_st_yMinROI = boost::any_cast<double>(val);}
        if("small_st_yMaxROI"==(*_i)->name){small_st_yMaxROI = boost::any_cast<double>(val);}
        if("small_st_zMinROI"==(*_i)->name){small_st_zMinROI = boost::any_cast<double>(val);}
        if("small_st_zMaxROI"==(*_i)->name){small_st_zMaxROI = boost::any_cast<double>(val);}
        if("small_st_xMinBoundingBox"==(*_i)->name){small_st_xMinBoundingBox = boost::any_cast<double>(val);}
        if("small_st_xMaxBoundingBox"==(*_i)->name){small_st_xMaxBoundingBox = boost::any_cast<double>(val);}
        if("small_st_yMinBoundingBox"==(*_i)->name){small_st_yMinBoundingBox = boost::any_cast<double>(val);}
        if("small_st_yMaxBoundingBox"==(*_i)->name){small_st_yMaxBoundingBox = boost::any_cast<double>(val);}
        if("small_st_zMinBoundingBox"==(*_i)->name){small_st_zMinBoundingBox = boost::any_cast<double>(val);}
        if("small_st_zMaxBoundingBox"==(*_i)->name){small_st_zMaxBoundingBox = boost::any_cast<double>(val);}
      }
    }

    int small_st_minPoints;
double small_st_epsilon;
int small_st_minClusterSize;
double small_st_maxClusterSize;
double small_st_xMinROI;
double small_st_xMaxROI;
double small_st_yMinROI;
double small_st_yMaxROI;
double small_st_zMinROI;
double small_st_zMaxROI;
double small_st_xMinBoundingBox;
double small_st_xMaxBoundingBox;
double small_st_yMinBoundingBox;
double small_st_yMaxBoundingBox;
double small_st_zMinBoundingBox;
double small_st_zMaxBoundingBox;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int small_st_minPoints;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_epsilon;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int small_st_minClusterSize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_maxClusterSize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_xMinROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_xMaxROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_yMinROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_yMaxROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_zMinROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_zMaxROI;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_xMinBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_xMaxBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_yMinBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_yMaxBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_zMinBoundingBox;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double small_st_zMaxBoundingBox;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("small_st_hyper_parameterConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const small_st_hyper_parameterConfig &__max__ = __getMax__();
      const small_st_hyper_parameterConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const small_st_hyper_parameterConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const small_st_hyper_parameterConfig &__getDefault__();
    static const small_st_hyper_parameterConfig &__getMax__();
    static const small_st_hyper_parameterConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const small_st_hyper_parameterConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void small_st_hyper_parameterConfig::ParamDescription<std::string>::clamp(small_st_hyper_parameterConfig &config, const small_st_hyper_parameterConfig &max, const small_st_hyper_parameterConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class small_st_hyper_parameterConfigStatics
  {
    friend class small_st_hyper_parameterConfig;

    small_st_hyper_parameterConfigStatics()
    {
small_st_hyper_parameterConfig::GroupDescription<small_st_hyper_parameterConfig::DEFAULT, small_st_hyper_parameterConfig> Default("Default", "", 0, 0, true, &small_st_hyper_parameterConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_minPoints = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_minPoints = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_minPoints = 30;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<int>("small_st_minPoints", "int", 0, "small_st_minPoints", "", &small_st_hyper_parameterConfig::small_st_minPoints)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<int>("small_st_minPoints", "int", 0, "small_st_minPoints", "", &small_st_hyper_parameterConfig::small_st_minPoints)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_epsilon = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_epsilon = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_epsilon = 0.4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_epsilon", "double", 0, "small_st_epsilon", "", &small_st_hyper_parameterConfig::small_st_epsilon)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_epsilon", "double", 0, "small_st_epsilon", "", &small_st_hyper_parameterConfig::small_st_epsilon)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_minClusterSize = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_minClusterSize = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_minClusterSize = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<int>("small_st_minClusterSize", "int", 0, "small_st_minClusterSize", "", &small_st_hyper_parameterConfig::small_st_minClusterSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<int>("small_st_minClusterSize", "int", 0, "small_st_minClusterSize", "", &small_st_hyper_parameterConfig::small_st_minClusterSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_maxClusterSize = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_maxClusterSize = 100000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_maxClusterSize = 5000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_maxClusterSize", "double", 0, "small_st_maxClusterSize", "", &small_st_hyper_parameterConfig::small_st_maxClusterSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_maxClusterSize", "double", 0, "small_st_maxClusterSize", "", &small_st_hyper_parameterConfig::small_st_maxClusterSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_xMinROI = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_xMinROI = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_xMinROI = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_xMinROI", "double", 0, "small_st_xMinROI", "", &small_st_hyper_parameterConfig::small_st_xMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_xMinROI", "double", 0, "small_st_xMinROI", "", &small_st_hyper_parameterConfig::small_st_xMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_xMaxROI = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_xMaxROI = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_xMaxROI = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_xMaxROI", "double", 0, "small_st_xMaxROI", "", &small_st_hyper_parameterConfig::small_st_xMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_xMaxROI", "double", 0, "small_st_xMaxROI", "", &small_st_hyper_parameterConfig::small_st_xMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_yMinROI = -200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_yMinROI = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_yMinROI = -1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_yMinROI", "double", 0, "small_st_yMinROI", "", &small_st_hyper_parameterConfig::small_st_yMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_yMinROI", "double", 0, "small_st_yMinROI", "", &small_st_hyper_parameterConfig::small_st_yMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_yMaxROI = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_yMaxROI = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_yMaxROI = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_yMaxROI", "double", 0, "small_st_yMaxROI", "", &small_st_hyper_parameterConfig::small_st_yMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_yMaxROI", "double", 0, "small_st_yMaxROI", "", &small_st_hyper_parameterConfig::small_st_yMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_zMinROI = -2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_zMinROI = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_zMinROI = -0.4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_zMinROI", "double", 0, "small_st_zMinROI", "", &small_st_hyper_parameterConfig::small_st_zMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_zMinROI", "double", 0, "small_st_zMinROI", "", &small_st_hyper_parameterConfig::small_st_zMinROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_zMaxROI = -2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_zMaxROI = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_zMaxROI = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_zMaxROI", "double", 0, "small_st_zMaxROI", "", &small_st_hyper_parameterConfig::small_st_zMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_zMaxROI", "double", 0, "small_st_zMaxROI", "", &small_st_hyper_parameterConfig::small_st_zMaxROI)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_xMinBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_xMinBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_xMinBoundingBox = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_xMinBoundingBox", "double", 0, "small_st_xMinBoundingBox", "", &small_st_hyper_parameterConfig::small_st_xMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_xMinBoundingBox", "double", 0, "small_st_xMinBoundingBox", "", &small_st_hyper_parameterConfig::small_st_xMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_xMaxBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_xMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_xMaxBoundingBox = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_xMaxBoundingBox", "double", 0, "small_st_xMaxBoundingBox", "", &small_st_hyper_parameterConfig::small_st_xMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_xMaxBoundingBox", "double", 0, "small_st_xMaxBoundingBox", "", &small_st_hyper_parameterConfig::small_st_xMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_yMinBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_yMinBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_yMinBoundingBox = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_yMinBoundingBox", "double", 0, "small_st_yMinBoundingBox", "", &small_st_hyper_parameterConfig::small_st_yMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_yMinBoundingBox", "double", 0, "small_st_yMinBoundingBox", "", &small_st_hyper_parameterConfig::small_st_yMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_yMaxBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_yMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_yMaxBoundingBox = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_yMaxBoundingBox", "double", 0, "small_st_yMaxBoundingBox", "", &small_st_hyper_parameterConfig::small_st_yMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_yMaxBoundingBox", "double", 0, "small_st_yMaxBoundingBox", "", &small_st_hyper_parameterConfig::small_st_yMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_zMinBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_zMinBoundingBox = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_zMinBoundingBox = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_zMinBoundingBox", "double", 0, "small_st_zMinBoundingBox", "", &small_st_hyper_parameterConfig::small_st_zMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_zMinBoundingBox", "double", 0, "small_st_zMinBoundingBox", "", &small_st_hyper_parameterConfig::small_st_zMinBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.small_st_zMaxBoundingBox = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.small_st_zMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.small_st_zMaxBoundingBox = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_zMaxBoundingBox", "double", 0, "small_st_zMaxBoundingBox", "", &small_st_hyper_parameterConfig::small_st_zMaxBoundingBox)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new small_st_hyper_parameterConfig::ParamDescription<double>("small_st_zMaxBoundingBox", "double", 0, "small_st_zMaxBoundingBox", "", &small_st_hyper_parameterConfig::small_st_zMaxBoundingBox)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(small_st_hyper_parameterConfig::AbstractGroupDescriptionConstPtr(new small_st_hyper_parameterConfig::GroupDescription<small_st_hyper_parameterConfig::DEFAULT, small_st_hyper_parameterConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<small_st_hyper_parameterConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<small_st_hyper_parameterConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    small_st_hyper_parameterConfig __max__;
    small_st_hyper_parameterConfig __min__;
    small_st_hyper_parameterConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const small_st_hyper_parameterConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static small_st_hyper_parameterConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &small_st_hyper_parameterConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const small_st_hyper_parameterConfig &small_st_hyper_parameterConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const small_st_hyper_parameterConfig &small_st_hyper_parameterConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const small_st_hyper_parameterConfig &small_st_hyper_parameterConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<small_st_hyper_parameterConfig::AbstractParamDescriptionConstPtr> &small_st_hyper_parameterConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<small_st_hyper_parameterConfig::AbstractGroupDescriptionConstPtr> &small_st_hyper_parameterConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const small_st_hyper_parameterConfigStatics *small_st_hyper_parameterConfig::__get_statics__()
  {
    const static small_st_hyper_parameterConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = small_st_hyper_parameterConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __SMALL_ST_HYPER_PARAMETERRECONFIGURATOR_H__
