// Generated by gencpp from file lidar_team_erp42/WaypointList.msg
// DO NOT EDIT!


#ifndef LIDAR_TEAM_ERP42_MESSAGE_WAYPOINTLIST_H
#define LIDAR_TEAM_ERP42_MESSAGE_WAYPOINTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lidar_team_erp42/Waypoint.h>

namespace lidar_team_erp42
{
template <class ContainerAllocator>
struct WaypointList_
{
  typedef WaypointList_<ContainerAllocator> Type;

  WaypointList_()
    : header()
    , info()  {
    }
  WaypointList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::lidar_team_erp42::Waypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidar_team_erp42::Waypoint_<ContainerAllocator> >::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::lidar_team_erp42::WaypointList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_team_erp42::WaypointList_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointList_

typedef ::lidar_team_erp42::WaypointList_<std::allocator<void> > WaypointList;

typedef boost::shared_ptr< ::lidar_team_erp42::WaypointList > WaypointListPtr;
typedef boost::shared_ptr< ::lidar_team_erp42::WaypointList const> WaypointListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_team_erp42::WaypointList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_team_erp42::WaypointList_<ContainerAllocator1> & lhs, const ::lidar_team_erp42::WaypointList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_team_erp42::WaypointList_<ContainerAllocator1> & lhs, const ::lidar_team_erp42::WaypointList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_team_erp42

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_team_erp42::WaypointList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_team_erp42::WaypointList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_team_erp42::WaypointList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5103fdd73a1575a4d565f16f08c82984";
  }

  static const char* value(const ::lidar_team_erp42::WaypointList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5103fdd73a1575a4ULL;
  static const uint64_t static_value2 = 0xd565f16f08c82984ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_team_erp42/WaypointList";
  }

  static const char* value(const ::lidar_team_erp42::WaypointList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"Waypoint[] info\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: lidar_team_erp42/Waypoint\n"
"int32 cnt\n"
"float32[200] x_arr\n"
"float32[200] y_arr\n"
;
  }

  static const char* value(const ::lidar_team_erp42::WaypointList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_team_erp42::WaypointList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_team_erp42::WaypointList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "info[]" << std::endl;
    for (size_t i = 0; i < v.info.size(); ++i)
    {
      s << indent << "  info[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_team_erp42::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_TEAM_ERP42_MESSAGE_WAYPOINTLIST_H
