(cl:in-package ublox_msgs-msg)
(cl:export '(VERSION-VAL
          VERSION
          RESERVED1-VAL
          RESERVED1
          INVALID_LLH-VAL
          INVALID_LLH
          ITOW-VAL
          ITOW
          LON-VAL
          LON
          LAT-VAL
          LAT
          HEIGHT-VAL
          HEIGHT
          HMSL-VAL
          HMSL
          LONHP-VAL
          LONHP
          LATHP-VAL
          LATHP
          HEIGHTHP-VAL
          HEIGHTHP
          HMSLHP-VAL
          HMSLHP
          HACC-VAL
          HACC
          VACC-VAL
          VACC
))