# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ublox_msgs/NavHPPOSLLH.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NavHPPOSLLH(genpy.Message):
  _md5sum = "9da6664837183254bd840fe05c8c1e4b"
  _type = "ublox_msgs/NavHPPOSLLH"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# NAV-HPPOSLLH (0x01 0x14)
# High Precision Geodetic Position Solution
#
# See important comments concerning validity of position given in section
# Navigation Output Filters.
# This message outputs the Geodetic position in the currently selected
# Ellipsoid. The default is the WGS84 Ellipsoid, but can be changed with the
# message CFG-DAT.
#

uint8 CLASS_ID = 1
uint8 MESSAGE_ID = 20

uint8 version
uint8[2] reserved1
int8 invalid_llh

uint32 iTOW             # GPS Millisecond Time of Week [ms]

int32 lon               # Longitude [deg / 1e-7]
int32 lat               # Latitude [deg / 1e-7]
int32 height            # Height above Ellipsoid [mm]
int32 hMSL              # Height above mean sea level [mm]
int8 lonHp              # Longitude [deg / 1e-9, range -99 to +99]
int8 latHp              # Latitude [deg / 1e-9, range -99 to +99]
int8 heightHp          # Height above Ellipsoid [mm / 0.1, range -9 to +9]
int8 hMSLHp            # Height above mean sea level [mm / 0.1, range -9 to +9]
uint32 hAcc             # Horizontal Accuracy Estimate [mm / 0.1]
uint32 vAcc             # Vertical Accuracy Estimate [mm / 0.1]
"""
  # Pseudo-constants
  CLASS_ID = 1
  MESSAGE_ID = 20

  __slots__ = ['version','reserved1','invalid_llh','iTOW','lon','lat','height','hMSL','lonHp','latHp','heightHp','hMSLHp','hAcc','vAcc']
  _slot_types = ['uint8','uint8[2]','int8','uint32','int32','int32','int32','int32','int8','int8','int8','int8','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       version,reserved1,invalid_llh,iTOW,lon,lat,height,hMSL,lonHp,latHp,heightHp,hMSLHp,hAcc,vAcc

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NavHPPOSLLH, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.version is None:
        self.version = 0
      if self.reserved1 is None:
        self.reserved1 = b'\0'*2
      if self.invalid_llh is None:
        self.invalid_llh = 0
      if self.iTOW is None:
        self.iTOW = 0
      if self.lon is None:
        self.lon = 0
      if self.lat is None:
        self.lat = 0
      if self.height is None:
        self.height = 0
      if self.hMSL is None:
        self.hMSL = 0
      if self.lonHp is None:
        self.lonHp = 0
      if self.latHp is None:
        self.latHp = 0
      if self.heightHp is None:
        self.heightHp = 0
      if self.hMSLHp is None:
        self.hMSLHp = 0
      if self.hAcc is None:
        self.hAcc = 0
      if self.vAcc is None:
        self.vAcc = 0
    else:
      self.version = 0
      self.reserved1 = b'\0'*2
      self.invalid_llh = 0
      self.iTOW = 0
      self.lon = 0
      self.lat = 0
      self.height = 0
      self.hMSL = 0
      self.lonHp = 0
      self.latHp = 0
      self.heightHp = 0
      self.hMSLHp = 0
      self.hAcc = 0
      self.vAcc = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.version
      buff.write(_get_struct_B().pack(_x))
      _x = self.reserved1
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_2B().pack(*_x))
      else:
        buff.write(_get_struct_2s().pack(_x))
      _x = self
      buff.write(_get_struct_bI4i4b2I().pack(_x.invalid_llh, _x.iTOW, _x.lon, _x.lat, _x.height, _x.hMSL, _x.lonHp, _x.latHp, _x.heightHp, _x.hMSLHp, _x.hAcc, _x.vAcc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.version,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 2
      self.reserved1 = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.invalid_llh, _x.iTOW, _x.lon, _x.lat, _x.height, _x.hMSL, _x.lonHp, _x.latHp, _x.heightHp, _x.hMSLHp, _x.hAcc, _x.vAcc,) = _get_struct_bI4i4b2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.version
      buff.write(_get_struct_B().pack(_x))
      _x = self.reserved1
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_2B().pack(*_x))
      else:
        buff.write(_get_struct_2s().pack(_x))
      _x = self
      buff.write(_get_struct_bI4i4b2I().pack(_x.invalid_llh, _x.iTOW, _x.lon, _x.lat, _x.height, _x.hMSL, _x.lonHp, _x.latHp, _x.heightHp, _x.hMSLHp, _x.hAcc, _x.vAcc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.version,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 2
      self.reserved1 = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.invalid_llh, _x.iTOW, _x.lon, _x.lat, _x.height, _x.hMSL, _x.lonHp, _x.latHp, _x.heightHp, _x.hMSLHp, _x.hAcc, _x.vAcc,) = _get_struct_bI4i4b2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_2s = None
def _get_struct_2s():
    global _struct_2s
    if _struct_2s is None:
        _struct_2s = struct.Struct("<2s")
    return _struct_2s
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_bI4i4b2I = None
def _get_struct_bI4i4b2I():
    global _struct_bI4i4b2I
    if _struct_bI4i4b2I is None:
        _struct_bI4i4b2I = struct.Struct("<bI4i4b2I")
    return _struct_bI4i4b2I
